export const CHANGE_GROUP_REQUEST = "CHANGE_GROUP_REQUEST";
export const CHANGE_GROUP_SUCCESS = "CHANGE_GROUP_SUCCESS";
export const CHANGE_GROUP_FAILURE = "CHANGE_GROUP_FAILURE";

export const FETCH_GROUPS_REQUEST = "FETCH_GROUPS_REQUEST";
export const FETCH_GROUPS_SUCCESS = "FETCH_GROUPS_SUCCESS";
export const FETCH_GROUPS_FAILURE = "FETCH_GROUPS_FAILURE";

export const FETCH_GROUP_REQUEST = "FETCH_GROUP_REQUEST";
export const FETCH_GROUP_SUCCESS = "FETCH_GROUP_SUCCESS";
export const FETCH_GROUP_FAILURE = "FETCH_GROUP_FAILURE";

export const CREATE_GROUP_REQUEST = "CREATE_GROUP_REQUEST";
export const CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS";
export const CREATE_GROUP_FAILURE = "CREATE_GROUP_FAILURE";

export const JOIN_GROUP_REQUEST = "JOIN_GROUP_REQUEST";
export const JOIN_GROUP_SUCCESS = "JOIN_GROUP_SUCCESS";
export const JOIN_GROUP_FAILURE = "JOIN_GROUP_FAILURE";

export const SEARCH_GROUPS_FAILURE = "SEARCH_GROUPS_FAILURE";
export const SEARCH_GROUPS_SUCCESS = "SEARCH_GROUPS_SUCCESS";
export const SEARCH_GROUPS_REQUEST = "SEARCH_GROUPS_REQUEST";

export const RELOAD_GROUPS_FAILURE = "RELOAD_GROUPS_FAILURE";
export const RELOAD_GROUPS_SUCCESS = "RELOAD_GROUPS_SUCCESS";
export const RELOAD_GROUPS_REQUEST = "RELOAD_GROUPS_REQUEST";
