export const FETCH_MOVIES_REQUEST = "FETCH_MOVIES_REQUEST";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_FAILURE = "FETCH_MOVIES_FAILURE";

export const FETCH_MOVIE_REQUEST = "FETCH_MOVIE_REQUEST";
export const FETCH_MOVIE_SUCCESS = "FETCH_MOVIE_SUCCESS";
export const FETCH_MOVIE_FAILURE = "FETCH_MOVIE_FAILURE";

export const SEARCH_MOVIES_FAILURE = "SEARCH_MOVIES_FAILURE";
export const SEARCH_MOVIES_SUCCESS = "SEARCH_MOVIES_SUCCESS";
export const SEARCH_MOVIES_REQUEST = "SEARCH_MOVIES_REQUEST";

export const SEARCH_CLEAR_FAILURE = "SEARCH_CLEAR_FAILURE";
export const SEARCH_CLEAR_SUCCESS = "SEARCH_CLEAR_SUCCESS";
export const SEARCH_CLEAR_REQUEST = "SEARCH_CLEAR_REQUEST";

export const ADD_MOVIE_REQUEST = "ADD_MOVIE_REQUEST";
export const ADD_MOVIE_SUCCESS = "ADD_MOVIE_SUCCESS";
export const ADD_MOVIE_FAILURE = "ADD_MOVIE_FAILURE";

export const RATE_MOVIE_REQUEST = "RATE_MOVIE_REQUEST";
export const RATE_MOVIE_SUCCESS = "RATE_MOVIE_SUCCESS";
export const RATE_MOVIE_FAILURE = "RATE_MOVIE_FAILURE";

export const UPDATE_MOVIES = "UPDATE_MOVIES";

export const RELOAD_MOVIES_FAILURE = "RELOAD_MOVIES_FAILURE";
export const RELOAD_MOVIES_SUCCESS = "RELOAD_MOVIES_SUCCESS";
export const RELOAD_MOVIES_REQUEST = "RELOAD_MOVIES_REQUEST";