export const THEME_SWITCH_FAILURE = "THEME_SWITCH_FAILURE";
export const THEME_SWITCH_SUCCESS = "THEME_SWITCH_SUCCESS";
export const THEME_SWITCH_REQUEST = "THEME_SWITCH_REQUEST";

export const RESTORE_THEME_FAILURE = "RESTORE_THEME_FAILURE";
export const RESTORE_THEME_SUCCESS = "RESTORE_THEME_SUCCESS";
export const RESTORE_THEME_REQUEST = "RESTORE_THEME_REQUEST";