export const IS_AUTHENTICATED_REQUEST = "IS_AUTHENTICATED_REQUEST";
export const IS_AUTHENTICATED_FAILURE = "IS_AUTHENTICATED_FAILURE";
export const IS_AUTHENTICATED_SUCCESS = "IS_AUTHENTICATED_SUCCESS";

export const RELOAD_USER_REQUEST = "RELOAD_USER_REQUEST";
export const RELOAD_USER_FAILURE = "RELOAD_USER_FAILURE";
export const RELOAD_USER_SUCCESS = "RELOAD_USER_SUCCESS";
