export const IS_AUTHENTICATED_REQUEST = "IS_AUTHENTICATED_REQUEST";
export const IS_AUTHENTICATED_FAILURE = "IS_AUTHENTICATED_FAILURE";
export const IS_AUTHENTICATED_SUCCESS = "IS_AUTHENTICATED_SUCCESS";